### ISSUE TITLE
repomd.xml does not match metalink error

### ISSUE THREAD

**Issue by deanpeterson** [jboss-dockerfiles/base-jdk#1] opened 2015-05-09 10:29 UTC
When I try to do a yum install -y git while building based on this container I get the following error:

 "Failed to connect to 2607:ff68:1:42::10: Network is unreachable"
http://mirror.cs.pitt.edu/fedora/linux/updates/20/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for updates

**Comment by goldmann** [comment] 2015-05-11 07:58
I could not reproduce it locally. This has something to do with your network set up. It tries to retrieve IPv6 address, is this what you want? How do you run the container? Which tag/image you used?

```
$ docker run -it --rm -u root jboss/base-jdk:7 bash
[root@09ea080c0934 jboss]# yum install -y git
fedora/20/x86_64/metalink                                                                                                                                                                                                                                          |  22 kB  00:00:00     
fedora                                                                                                                                                                                                                                                             | 3.8 kB  00:00:00     
updates/20/x86_64/metalink                                                                                                                                                                                                                                         |  21 kB  00:00:00     
updates                                                                                                                                                                                                                                                            | 4.9 kB  00:00:00     
(1/4): updates/20/x86_64/group_gz                                                                                                                                                                                                                                  | 239 kB  00:00:01     
(2/4): fedora/20/x86_64/group_gz                                                                                                                                                                                                                                   | 394 kB  00:00:03     
(3/4): fedora/20/x86_64/primary_db                                                                                                                                                                                                                                 |  18 MB  00:00:40     
(4/4): updates/20/x86_64/primary_db                                                                                                                                                                                                                                |  11 MB  00:00:56     
updates/20/x86_64/pkgtags      FAILED                                                                                                                                                                                                                      0.0 B/s |    0 B  00:00:00     
http://ftp.acc.umu.se/mirror/fedora/linux/updates/20/x86_64/repodata/09563e5169e164470d9a91da4377584d3ad601d16cbe868a2aa12b3753f54169-pkgtags.sqlite.gz: [Errno 14] HTTP Error 404 - Not Found                                                             0.0 B/s |    0 B  00:00:00     
Trying other mirror.
updates/20/x86_64/pkgtags      FAILED                                                                                                                                                                                                                     347 kB/s | 385 kB  00:00:01     
http://ftp.up.pt/fedora/updates/20/x86_64/repodata/09563e5169e164470d9a91da4377584d3ad601d16cbe868a2aa12b3753f54169-pkgtags.sqlite.gz: [Errno 14] HTTP Error 404 - Not Found                                                                              347 kB/s | 385 kB  00:00:01     
Trying other mirror.
updates/20/x86_64/pkgtags      FAILED                                                                                                                                                                                                                     384 kB/s | 681 kB  00:00:01     
http://mirror.proserve.nl/fedora/linux/updates/20/x86_64/repodata/09563e5169e164470d9a91da4377584d3ad601d16cbe868a2aa12b3753f54169-pkgtags.sqlite.gz: [Errno 14] HTTP Error 404 - Not Found                                                               384 kB/s | 681 kB  00:00:01     
Trying other mirror.
updates/20/x86_64/pkgtags      FAILED                                                                                                                                                                                                                     430 kB/s | 1.1 MB  00:00:02     
http://mirror.1000mbps.com/fedora/linux/updates/20/x86_64/repodata/09563e5169e164470d9a91da4377584d3ad601d16cbe868a2aa12b3753f54169-pkgtags.sqlite.gz: [Errno 14] HTTP Error 404 - Not Found                                                              430 kB/s | 1.1 MB  00:00:02     
Trying other mirror.
(1/2): updates/20/x86_64/updateinfo                                                                                                                                                                                                                                | 1.9 MB  00:00:03     
(2/2): updates/20/x86_64/pkgtags                                                                                                                                                                                                                                   | 1.5 MB  00:00:04     
Resolving Dependencies
--> Running transaction check
---> Package git.x86_64 0:1.9.3-2.fc20 will be installed
--> Processing Dependency: perl-Git = 1.9.3-2.fc20 for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl >= 5.008 for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl(warnings) for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl(strict) for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl(lib) for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl(Term::ReadKey) for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl(Git) for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl(Getopt::Long) for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl(File::stat) for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl(File::Temp) for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl(File::Spec) for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl(File::Path) for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl(File::Find) for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl(File::Copy) for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl(File::Basename) for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: perl(Error) for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: /usr/bin/perl for package: git-1.9.3-2.fc20.x86_64
--> Processing Dependency: libgnome-keyring.so.0()(64bit) for package: git-1.9.3-2.fc20.x86_64
--> Running transaction check
---> Package libgnome-keyring.x86_64 0:3.10.1-1.fc20 will be installed
---> Package perl.x86_64 4:5.18.4-293.fc20 will be installed
--> Processing Dependency: perl-libs = 4:5.18.4-293.fc20 for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(Socket) >= 1.3 for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(Scalar::Util) >= 1.10 for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl-macros for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl-libs for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(threads::shared) for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(threads) for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(constant) for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(Time::Local) for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(Time::HiRes) for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(Storable) for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(Socket) for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(Scalar::Util) for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(Pod::Simple::XHTML) for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(Pod::Simple::Search) for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(Module::CoreList) for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(Filter::Util::Call) for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(Exporter) for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: perl(Carp) for package: 4:perl-5.18.4-293.fc20.x86_64
--> Processing Dependency: libperl.so.5.18()(64bit) for package: 4:perl-5.18.4-293.fc20.x86_64
---> Package perl-Error.noarch 1:0.17021-1.fc20 will be installed
---> Package perl-File-Path.noarch 0:2.09-292.fc20 will be installed
---> Package perl-File-Temp.noarch 0:0.23.01-4.fc20 will be installed
---> Package perl-Getopt-Long.noarch 0:2.45-1.fc20 will be installed
--> Processing Dependency: perl(Pod::Usage) >= 1.14 for package: perl-Getopt-Long-2.45-1.fc20.noarch
--> Processing Dependency: perl(Text::ParseWords) for package: perl-Getopt-Long-2.45-1.fc20.noarch
---> Package perl-Git.noarch 0:1.9.3-2.fc20 will be installed
---> Package perl-PathTools.x86_64 0:3.40-291.fc20 will be installed
---> Package perl-TermReadKey.x86_64 0:2.30-20.fc20 will be installed
--> Running transaction check
---> Package perl-Carp.noarch 0:1.26-245.fc20 will be installed
---> Package perl-Exporter.noarch 0:5.70-1.fc20 will be installed
---> Package perl-Filter.x86_64 1:1.54-1.fc20 will be installed
---> Package perl-Module-CoreList.noarch 1:3.13-293.fc20 will be installed
--> Processing Dependency: perl(version) for package: 1:perl-Module-CoreList-3.13-293.fc20.noarch
---> Package perl-Pod-Simple.noarch 1:3.29-1.fc20 will be installed
--> Processing Dependency: perl(Pod::Escapes) >= 1.04 for package: 1:perl-Pod-Simple-3.29-1.fc20.noarch
--> Processing Dependency: perl(Encode) for package: 1:perl-Pod-Simple-3.29-1.fc20.noarch
---> Package perl-Pod-Usage.noarch 4:1.66-1.fc20 will be installed
--> Processing Dependency: perl(Pod::Text) >= 3.15 for package: 4:perl-Pod-Usage-1.66-1.fc20.noarch
--> Processing Dependency: perl-Pod-Perldoc for package: 4:perl-Pod-Usage-1.66-1.fc20.noarch
---> Package perl-Scalar-List-Utils.x86_64 0:1.31-293.fc20 will be installed
---> Package perl-Socket.x86_64 1:2.018-1.fc20 will be installed
---> Package perl-Storable.x86_64 0:2.51-1.fc20 will be installed
---> Package perl-Text-ParseWords.noarch 0:3.30-1.fc20 will be installed
---> Package perl-Time-HiRes.x86_64 0:1.9726-1.fc20 will be installed
---> Package perl-Time-Local.noarch 0:1.2300-291.fc20 will be installed
---> Package perl-constant.noarch 0:1.27-292.fc20 will be installed
---> Package perl-libs.x86_64 4:5.18.4-293.fc20 will be installed
---> Package perl-macros.x86_64 4:5.18.4-293.fc20 will be installed
---> Package perl-threads.x86_64 1:1.92-1.fc20 will be installed
---> Package perl-threads-shared.x86_64 0:1.46-1.fc20 will be installed
--> Running transaction check
---> Package perl-Encode.x86_64 1:2.54-4.fc20 will be installed
---> Package perl-Pod-Escapes.noarch 1:1.04-293.fc20 will be installed
---> Package perl-Pod-Perldoc.noarch 0:3.20-7.fc20 will be installed
--> Processing Dependency: perl(parent) for package: perl-Pod-Perldoc-3.20-7.fc20.noarch
--> Processing Dependency: perl(HTTP::Tiny) for package: perl-Pod-Perldoc-3.20-7.fc20.noarch
---> Package perl-podlators.noarch 0:2.5.1-291.fc20 will be installed
---> Package perl-version.x86_64 3:0.99.07-1.fc20 will be installed
--> Running transaction check
---> Package perl-HTTP-Tiny.noarch 0:0.034-4.fc20 will be installed
---> Package perl-parent.noarch 1:0.228-1.fc20 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==========================================================================================================================================================================================================================================================================================
 Package                                                                      Arch                                                         Version                                                                    Repository                                                     Size
==========================================================================================================================================================================================================================================================================================
Installing:
 git                                                                          x86_64                                                       1.9.3-2.fc20                                                               updates                                                       4.7 M
Installing for dependencies:
 libgnome-keyring                                                             x86_64                                                       3.10.1-1.fc20                                                              fedora                                                        110 k
 perl                                                                         x86_64                                                       4:5.18.4-293.fc20                                                          updates                                                       8.2 M
 perl-Carp                                                                    noarch                                                       1.26-245.fc20                                                              fedora                                                         19 k
 perl-Encode                                                                  x86_64                                                       1:2.54-4.fc20                                                              updates                                                       1.5 M
 perl-Error                                                                   noarch                                                       1:0.17021-1.fc20                                                           fedora                                                         32 k
 perl-Exporter                                                                noarch                                                       5.70-1.fc20                                                                updates                                                        29 k
 perl-File-Path                                                               noarch                                                       2.09-292.fc20                                                              fedora                                                         27 k
 perl-File-Temp                                                               noarch                                                       0.23.01-4.fc20                                                             fedora                                                         57 k
 perl-Filter                                                                  x86_64                                                       1:1.54-1.fc20                                                              updates                                                        79 k
 perl-Getopt-Long                                                             noarch                                                       2.45-1.fc20                                                                updates                                                        57 k
 perl-Git                                                                     noarch                                                       1.9.3-2.fc20                                                               updates                                                        54 k
 perl-HTTP-Tiny                                                               noarch                                                       0.034-4.fc20                                                               updates                                                        39 k
 perl-Module-CoreList                                                         noarch                                                       1:3.13-293.fc20                                                            updates                                                        98 k
 perl-PathTools                                                               x86_64                                                       3.40-291.fc20                                                              fedora                                                         83 k
 perl-Pod-Escapes                                                             noarch                                                       1:1.04-293.fc20                                                            updates                                                        52 k
 perl-Pod-Perldoc                                                             noarch                                                       3.20-7.fc20                                                                fedora                                                         87 k
 perl-Pod-Simple                                                              noarch                                                       1:3.29-1.fc20                                                              updates                                                       217 k
 perl-Pod-Usage                                                               noarch                                                       4:1.66-1.fc20                                                              updates                                                        29 k
 perl-Scalar-List-Utils                                                       x86_64                                                       1.31-293.fc20                                                              fedora                                                         43 k
 perl-Socket                                                                  x86_64                                                       1:2.018-1.fc20                                                             updates                                                        50 k
 perl-Storable                                                                x86_64                                                       2.51-1.fc20                                                                updates                                                        78 k
 perl-TermReadKey                                                             x86_64                                                       2.30-20.fc20                                                               fedora                                                         31 k
 perl-Text-ParseWords                                                         noarch                                                       3.30-1.fc20                                                                updates                                                        13 k
 perl-Time-HiRes                                                              x86_64                                                       1.9726-1.fc20                                                              fedora                                                         46 k
 perl-Time-Local                                                              noarch                                                       1.2300-291.fc20                                                            fedora                                                         25 k
 perl-constant                                                                noarch                                                       1.27-292.fc20                                                              fedora                                                         19 k
 perl-libs                                                                    x86_64                                                       4:5.18.4-293.fc20                                                          updates                                                       694 k
 perl-macros                                                                  x86_64                                                       4:5.18.4-293.fc20                                                          updates                                                        44 k
 perl-parent                                                                  noarch                                                       1:0.228-1.fc20                                                             fedora                                                         13 k
 perl-podlators                                                               noarch                                                       2.5.1-291.fc20                                                             fedora                                                        112 k
 perl-threads                                                                 x86_64                                                       1:1.92-1.fc20                                                              updates                                                        50 k
 perl-threads-shared                                                          x86_64                                                       1.46-1.fc20                                                                updates                                                        39 k
 perl-version                                                                 x86_64                                                       3:0.99.07-1.fc20                                                           updates                                                        84 k

Transaction Summary
==========================================================================================================================================================================================================================================================================================
Install  1 Package (+33 Dependent packages)

Total download size: 17 M
Installed size: 62 M
Downloading packages:
(1/34): perl-Carp-1.26-245.fc20.noarch.rpm                                                                                                                                                                                                                         |  19 kB  00:00:00     
(2/34): perl-Error-0.17021-1.fc20.noarch.rpm                                                                                                                                                                                                                       |  32 kB  00:00:00     
(3/34): perl-Exporter-5.70-1.fc20.noarch.rpm                                                                                                                                                                                                                       |  29 kB  00:00:00     
(4/34): libgnome-keyring-3.10.1-1.fc20.x86_64.rpm                                                                                                                                                                                                                  | 110 kB  00:00:01     
(5/34): perl-File-Path-2.09-292.fc20.noarch.rpm                                                                                                                                                                                                                    |  27 kB  00:00:00     
(6/34): perl-File-Temp-0.23.01-4.fc20.noarch.rpm                                                                                                                                                                                                                   |  57 kB  00:00:00     
(7/34): perl-Filter-1.54-1.fc20.x86_64.rpm                                                                                                                                                                                                                         |  79 kB  00:00:00     
(8/34): perl-Git-1.9.3-2.fc20.noarch.rpm                                                                                                                                                                                                                           |  54 kB  00:00:00     
(9/34): perl-HTTP-Tiny-0.034-4.fc20.noarch.rpm                                                                                                                                                                                                                     |  39 kB  00:00:00     
(10/34): perl-Encode-2.54-4.fc20.x86_64.rpm                                                                                                                                                                                                                        | 1.5 MB  00:00:04     
(11/34): perl-Module-CoreList-3.13-293.fc20.noarch.rpm                                                                                                                                                                                                             |  98 kB  00:00:01     
(12/34): perl-Getopt-Long-2.45-1.fc20.noarch.rpm                                                                                                                                                                                                                   |  57 kB  00:00:03     
(13/34): perl-PathTools-3.40-291.fc20.x86_64.rpm                                                                                                                                                                                                                   |  83 kB  00:00:01     
(14/34): perl-Pod-Escapes-1.04-293.fc20.noarch.rpm                                                                                                                                                                                                                 |  52 kB  00:00:01     
(15/34): perl-Pod-Usage-1.66-1.fc20.noarch.rpm                                                                                                                                                                                                                     |  29 kB  00:00:00     
(16/34): perl-Pod-Perldoc-3.20-7.fc20.noarch.rpm                                                                                                                                                                                                                   |  87 kB  00:00:02     
(17/34): perl-Scalar-List-Utils-1.31-293.fc20.x86_64.rpm                                                                                                                                                                                                           |  43 kB  00:00:01     
(18/34): perl-Socket-2.018-1.fc20.x86_64.rpm                                                                                                                                                                                                                       |  50 kB  00:00:00     
(19/34): perl-Pod-Simple-3.29-1.fc20.noarch.rpm                                                                                                                                                                                                                    | 217 kB  00:00:03     
(20/34): perl-TermReadKey-2.30-20.fc20.x86_64.rpm                                                                                                                                                                                                                  |  31 kB  00:00:03     
(21/34): perl-Text-ParseWords-3.30-1.fc20.noarch.rpm                                                                                                                                                                                                               |  13 kB  00:00:03     
(22/34): perl-Storable-2.51-1.fc20.x86_64.rpm                                                                                                                                                                                                                      |  78 kB  00:00:03     
(23/34): git-1.9.3-2.fc20.x86_64.rpm                                                                                                                                                                                                                               | 4.7 MB  00:00:13     
(24/34): perl-Time-Local-1.2300-291.fc20.noarch.rpm                                                                                                                                                                                                                |  25 kB  00:00:01     
(25/34): perl-Time-HiRes-1.9726-1.fc20.x86_64.rpm                                                                                                                                                                                                                  |  46 kB  00:00:01     
(26/34): perl-constant-1.27-292.fc20.noarch.rpm                                                                                                                                                                                                                    |  19 kB  00:00:02     
(27/34): perl-macros-5.18.4-293.fc20.x86_64.rpm                                                                                                                                                                                                                    |  44 kB  00:00:01     
(28/34): perl-parent-0.228-1.fc20.noarch.rpm                                                                                                                                                                                                                       |  13 kB  00:00:00     
(29/34): perl-threads-1.92-1.fc20.x86_64.rpm                                                                                                                                                                                                                       |  50 kB  00:00:00     
(30/34): perl-libs-5.18.4-293.fc20.x86_64.rpm                                                                                                                                                                                                                      | 694 kB  00:00:07     
(31/34): perl-threads-shared-1.46-1.fc20.x86_64.rpm                                                                                                                                                                                                                |  39 kB  00:00:07     
(32/34): perl-version-0.99.07-1.fc20.x86_64.rpm                                                                                                                                                                                                                    |  84 kB  00:00:07     
(33/34): perl-podlators-2.5.1-291.fc20.noarch.rpm                                                                                                                                                                                                                  | 112 kB  00:00:09     
(34/34): perl-5.18.4-293.fc20.x86_64.rpm                                                                                                                                                                                                                           | 8.2 MB  00:00:24     
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                                                                     699 kB/s |  17 MB  00:00:24     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 1:perl-parent-0.228-1.fc20.noarch                                                                                                                                                                                                                                     1/34 
  Installing : perl-HTTP-Tiny-0.034-4.fc20.noarch                                                                                                                                                                                                                                    2/34 
  Installing : perl-podlators-2.5.1-291.fc20.noarch                                                                                                                                                                                                                                  3/34 
  Installing : perl-Pod-Perldoc-3.20-7.fc20.noarch                                                                                                                                                                                                                                   4/34 
  Installing : 1:perl-Pod-Escapes-1.04-293.fc20.noarch                                                                                                                                                                                                                               5/34 
  Installing : 3:perl-version-0.99.07-1.fc20.x86_64                                                                                                                                                                                                                                  6/34 
  Installing : perl-Text-ParseWords-3.30-1.fc20.noarch                                                                                                                                                                                                                               7/34 
  Installing : 1:perl-Encode-2.54-4.fc20.x86_64                                                                                                                                                                                                                                      8/34 
  Installing : 4:perl-Pod-Usage-1.66-1.fc20.noarch                                                                                                                                                                                                                                   9/34 
  Installing : 4:perl-libs-5.18.4-293.fc20.x86_64                                                                                                                                                                                                                                   10/34 
  Installing : 4:perl-macros-5.18.4-293.fc20.x86_64                                                                                                                                                                                                                                 11/34 
  Installing : perl-Exporter-5.70-1.fc20.noarch                                                                                                                                                                                                                                     12/34 
  Installing : perl-Scalar-List-Utils-1.31-293.fc20.x86_64                                                                                                                                                                                                                          13/34 
  Installing : 1:perl-Filter-1.54-1.fc20.x86_64                                                                                                                                                                                                                                     14/34 
  Installing : 1:perl-Socket-2.018-1.fc20.x86_64                                                                                                                                                                                                                                    15/34 
  Installing : perl-Time-Local-1.2300-291.fc20.noarch                                                                                                                                                                                                                               16/34 
  Installing : perl-constant-1.27-292.fc20.noarch                                                                                                                                                                                                                                   17/34 
  Installing : perl-Storable-2.51-1.fc20.x86_64                                                                                                                                                                                                                                     18/34 
  Installing : perl-File-Path-2.09-292.fc20.noarch                                                                                                                                                                                                                                  19/34 
  Installing : perl-PathTools-3.40-291.fc20.x86_64                                                                                                                                                                                                                                  20/34 
  Installing : 1:perl-Module-CoreList-3.13-293.fc20.noarch                                                                                                                                                                                                                          21/34 
  Installing : 1:perl-Pod-Simple-3.29-1.fc20.noarch                                                                                                                                                                                                                                 22/34 
  Installing : perl-Getopt-Long-2.45-1.fc20.noarch                                                                                                                                                                                                                                  23/34 
  Installing : perl-File-Temp-0.23.01-4.fc20.noarch                                                                                                                                                                                                                                 24/34 
  Installing : perl-threads-shared-1.46-1.fc20.x86_64                                                                                                                                                                                                                               25/34 
  Installing : 1:perl-threads-1.92-1.fc20.x86_64                                                                                                                                                                                                                                    26/34 
  Installing : perl-Carp-1.26-245.fc20.noarch                                                                                                                                                                                                                                       27/34 
  Installing : perl-Time-HiRes-1.9726-1.fc20.x86_64                                                                                                                                                                                                                                 28/34 
  Installing : 4:perl-5.18.4-293.fc20.x86_64                                                                                                                                                                                                                                        29/34 
  Installing : 1:perl-Error-0.17021-1.fc20.noarch                                                                                                                                                                                                                                   30/34 
  Installing : perl-TermReadKey-2.30-20.fc20.x86_64                                                                                                                                                                                                                                 31/34 
  Installing : libgnome-keyring-3.10.1-1.fc20.x86_64                                                                                                                                                                                                                                32/34 
  Installing : perl-Git-1.9.3-2.fc20.noarch                                                                                                                                                                                                                                         33/34 
  Installing : git-1.9.3-2.fc20.x86_64                                                                                                                                                                                                                                              34/34 
  Verifying  : perl-Time-HiRes-1.9726-1.fc20.x86_64                                                                                                                                                                                                                                  1/34 
  Verifying  : perl-Exporter-5.70-1.fc20.noarch                                                                                                                                                                                                                                      2/34 
  Verifying  : perl-Time-Local-1.2300-291.fc20.noarch                                                                                                                                                                                                                                3/34 
  Verifying  : 1:perl-Encode-2.54-4.fc20.x86_64                                                                                                                                                                                                                                      4/34 
  Verifying  : git-1.9.3-2.fc20.x86_64                                                                                                                                                                                                                                               5/34 
  Verifying  : perl-threads-shared-1.46-1.fc20.x86_64                                                                                                                                                                                                                                6/34 
  Verifying  : 1:perl-Module-CoreList-3.13-293.fc20.noarch                                                                                                                                                                                                                           7/34 
  Verifying  : 4:perl-Pod-Usage-1.66-1.fc20.noarch                                                                                                                                                                                                                                   8/34 
  Verifying  : libgnome-keyring-3.10.1-1.fc20.x86_64                                                                                                                                                                                                                                 9/34 
  Verifying  : 1:perl-Error-0.17021-1.fc20.noarch                                                                                                                                                                                                                                   10/34 
  Verifying  : perl-Scalar-List-Utils-1.31-293.fc20.x86_64                                                                                                                                                                                                                          11/34 
  Verifying  : 1:perl-Pod-Simple-3.29-1.fc20.noarch                                                                                                                                                                                                                                 12/34 
  Verifying  : perl-HTTP-Tiny-0.034-4.fc20.noarch                                                                                                                                                                                                                                   13/34 
  Verifying  : 1:perl-Pod-Escapes-1.04-293.fc20.noarch                                                                                                                                                                                                                              14/34 
  Verifying  : 1:perl-Filter-1.54-1.fc20.x86_64                                                                                                                                                                                                                                     15/34 
  Verifying  : perl-Git-1.9.3-2.fc20.noarch                                                                                                                                                                                                                                         16/34 
  Verifying  : perl-TermReadKey-2.30-20.fc20.x86_64                                                                                                                                                                                                                                 17/34 
  Verifying  : 1:perl-Socket-2.018-1.fc20.x86_64                                                                                                                                                                                                                                    18/34 
  Verifying  : perl-constant-1.27-292.fc20.noarch                                                                                                                                                                                                                                   19/34 
  Verifying  : perl-Storable-2.51-1.fc20.x86_64                                                                                                                                                                                                                                     20/34 
  Verifying  : perl-File-Path-2.09-292.fc20.noarch                                                                                                                                                                                                                                  21/34 
  Verifying  : perl-Pod-Perldoc-3.20-7.fc20.noarch                                                                                                                                                                                                                                  22/34 
  Verifying  : perl-podlators-2.5.1-291.fc20.noarch                                                                                                                                                                                                                                 23/34 
  Verifying  : 1:perl-parent-0.228-1.fc20.noarch                                                                                                                                                                                                                                    24/34 
  Verifying  : 3:perl-version-0.99.07-1.fc20.x86_64                                                                                                                                                                                                                                 25/34 
  Verifying  : 4:perl-libs-5.18.4-293.fc20.x86_64                                                                                                                                                                                                                                   26/34 
  Verifying  : perl-PathTools-3.40-291.fc20.x86_64                                                                                                                                                                                                                                  27/34 
  Verifying  : 4:perl-macros-5.18.4-293.fc20.x86_64                                                                                                                                                                                                                                 28/34 
  Verifying  : perl-Text-ParseWords-3.30-1.fc20.noarch                                                                                                                                                                                                                              29/34 
  Verifying  : 4:perl-5.18.4-293.fc20.x86_64                                                                                                                                                                                                                                        30/34 
  Verifying  : perl-File-Temp-0.23.01-4.fc20.noarch                                                                                                                                                                                                                                 31/34 
  Verifying  : perl-Getopt-Long-2.45-1.fc20.noarch                                                                                                                                                                                                                                  32/34 
  Verifying  : 1:perl-threads-1.92-1.fc20.x86_64                                                                                                                                                                                                                                    33/34 
  Verifying  : perl-Carp-1.26-245.fc20.noarch                                                                                                                                                                                                                                       34/34 

Installed:
  git.x86_64 0:1.9.3-2.fc20                                                                                                                                                                                                                                                               

Dependency Installed:
  libgnome-keyring.x86_64 0:3.10.1-1.fc20            perl.x86_64 4:5.18.4-293.fc20                 perl-Carp.noarch 0:1.26-245.fc20             perl-Encode.x86_64 1:2.54-4.fc20            perl-Error.noarch 1:0.17021-1.fc20             perl-Exporter.noarch 0:5.70-1.fc20         
  perl-File-Path.noarch 0:2.09-292.fc20              perl-File-Temp.noarch 0:0.23.01-4.fc20        perl-Filter.x86_64 1:1.54-1.fc20             perl-Getopt-Long.noarch 0:2.45-1.fc20       perl-Git.noarch 0:1.9.3-2.fc20                 perl-HTTP-Tiny.noarch 0:0.034-4.fc20       
  perl-Module-CoreList.noarch 1:3.13-293.fc20        perl-PathTools.x86_64 0:3.40-291.fc20         perl-Pod-Escapes.noarch 1:1.04-293.fc20      perl-Pod-Perldoc.noarch 0:3.20-7.fc20       perl-Pod-Simple.noarch 1:3.29-1.fc20           perl-Pod-Usage.noarch 4:1.66-1.fc20        
  perl-Scalar-List-Utils.x86_64 0:1.31-293.fc20      perl-Socket.x86_64 1:2.018-1.fc20             perl-Storable.x86_64 0:2.51-1.fc20           perl-TermReadKey.x86_64 0:2.30-20.fc20      perl-Text-ParseWords.noarch 0:3.30-1.fc20      perl-Time-HiRes.x86_64 0:1.9726-1.fc20     
  perl-Time-Local.noarch 0:1.2300-291.fc20           perl-constant.noarch 0:1.27-292.fc20          perl-libs.x86_64 4:5.18.4-293.fc20           perl-macros.x86_64 4:5.18.4-293.fc20        perl-parent.noarch 1:0.228-1.fc20              perl-podlators.noarch 0:2.5.1-291.fc20     
  perl-threads.x86_64 1:1.92-1.fc20                  perl-threads-shared.x86_64 0:1.46-1.fc20      perl-version.x86_64 3:0.99.07-1.fc20        

Complete!
```

**Comment by gustavonalle** [comment] 2015-07-21 19:36
Apparently if in my Dockerfile i have:
```FROM jboss/base-jdk:8```

and try to build the image, the network is disabled.

**Comment by goldmann** [comment] 2015-08-04 09:05
Closing because there was no reply, assuming it's not an issue anymore.

**Closed as completed by goldmann** 2015-08-04 09:05 UTC
